config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => 'welcome#index'
  resources :welcome, :only => :index
  resources :comics do
    resources :pages
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comic.rb
class Comic < ActiveRecord::Base
  has_many :pages
  belongs_to :user

  validates :title, :presence => true
  validates :description, :presence => true

  has_attached_file :cover, :styles => { :medium => "500x500>", :thumb => "100x100>" }, :default_url => "/img/:style/missing.png"

  validates_attachment_content_type :cover, :content_type => /\Aimage\/.*\Z/
end

app/models/page.rb
class Page < ActiveRecord::Base
  belongs_to :comic
  validates :number, :presence => true

  has_attached_file :image, :styles => { :medium => "500x500>", :thumb => "100x100>" }, :default_url => "/img/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :comics

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/img/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def authorize
    if !current_user
      flash[:alert] = "Please sign in to visit this page."
      redirect_to '/'
    end
  end

  def authorize_admin
    if current_user.admin === true
      new_location_path
    else
      flash[:alert] = "Only an admin can visit this page."
      redirect_to '/'
    end
  end

  def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
      devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password, :avatar, :cover, :image) }
  end
end

app/controllers/comics_controller.rb
class ComicsController < ApplicationController
  before_action :authorize, only: [:new, :edit]
  # before_action :authorize_admin, only: [:new, :edit]
  def index
    @comic = Comic.all
  end

  def show
    @comic =Comic.find(params[:id])
  end

  def new
    @comic = Comic.new
  end

  def create
    @comic = current_user.comics.create(comic_params)

      if @comic.save
        flash[:notice] = "Comic Successfully Added"
        redirect_to comics_path
      else
        render :new
      end
    end

  def edit
    @comic = Comic.find(params[:id])
  end

  def update
    @comic = Comic.find(params[:id])
    if @comic.update(comic_params)
      redirect_to comics_path
    else
      render :edit
    end
  end

  def destroy
    @comic = Comic.find(params[:id])
    @comic.destroy
    redirect_to comics_path
  end

  private

    def comic_params
      params.require(:comic).permit(:user_id, :title, :description, :cover)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # before_action :authorize, only: [:new, :edit]
  # before_action :authorize_admin, only: [:new, :edit]
  def index
    @comic =Comic.find(params[:comic_id])
    @page = @comic.pages.all
  end

  def show
    @page =Page.find(params[:id])
  end

  def new
    @comic =Comic.find(params[:comic_id])

    @page = @comic.pages.new
  end

  def create
    @comic = Comic.find(params[:comic_id])
    @page = @comic.pages.new(page_params)
    if @page.save
      redirect_to comic_pages_path(@page.comic)
    else
      render :new
    end
  end

  private

    def page_params
      params.require(:page).permit(:comic_id, :number, :image)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comics_helper.rb
module ComicsHelper
end

app/views/comics/edit.html.erb
<h1>Edit <%= @comic.title %></h1>
<%= form_for @comic do |f| %>
<div class="field">
  <div class="form-group">
      <%= f.label :cover, class: 'col-sm-2 control-label'  %>
      <div class="col-sm-6">
          <%= f.file_field :cover %>
      </div>
  </div>
  <br><br>
  <%= f.label :title %><br />
  <%= f.text_field :title %>
</div>
<div class="actions">
  <%= f.submit "Update" %>
</div>

<button class="btn ">
  <%= link_to "Delete This Location", comic_path(@comic),
                    :data => {:confirm => "Are you sure?",
                    :method => "delete"} %>
                  </button>
<% end %>

app/views/comics/index.html.erb
<div class="title_container">
  <h1 id="comics">All Comics</h1>
</div>
<div class="welcome_container">
<ul style="list-style-type:none">
   <% @comic.each do |comic| %>
   <li>
     <hr class="style18">
     <div class="row">
       <div class="col-md-3">
           <%= image_tag(comic.cover.url(:thumb))%>
       </div>
       <div class="col-md-1">
       </div>
       <br>
       <div class="col-md-8">
         <h4 id="marker"><%= comic.title %></h4>
         <b>by <%= comic.user.email %> |</b>
         <%= link_to "Read it!", comic_path(comic) %>
       </div>
   </li>
   <% end %>
 </ul>
 <br>
 <br>
 <div class="right">
   <button class="btn btn-lg btn-primary"><%= link_to "Create a comic", new_comic_path, {:style=>'color:#FFFFFF;', :class => "css_class"} %></button>
 </div>

 </div>

app/views/comics/new.html.erb
<h1>Start Your Comic!</h1>
<%= form_for @comic do |f| %>
<div class="form-group">
    <%= f.label :cover, class: 'col-sm-2 control-label'  %>
    <div class="col-sm-6">
        <%= f.file_field :cover %>
    </div>
</div>
<br><br>

<div class="field">
  <%= f.hidden_field :user_id, value: current_user.id %><br />
</div>

<div class="field">
  <%= f.label :title %><br />
  <%= f.text_field :title %>
</div>

<div class="field">
  <%= f.label :description %><br />
  <%= f.text_field :description %>
</div>

<div class="actions">
  <%= f.submit "Create" %>
</div>
<% end %>

app/views/comics/show.html.erb
<div class="title_container">
  <h1><%=@comic.title%></h1>
</div>
<div class="cover">
  <%= image_tag(@comic.cover.url(:original)) %>
</div>
<div class="title_container">
  <h1>By <%=@comic.user.email%></h1>
</div>
<br>
<br>

  <button class="btn btn-info"><%= link_to "Go Back to All Comics", comics_path %></button>
<br><br>

  <button class="btn btn-info"><%= link_to "Edit Comic", edit_comic_path(@comic) %></button>

app/views/layouts/_menu.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <%= link_to "|  Ink About It  |", root_path, class: 'navbar-brand' %>

            <%= link_to "|  All Comics  |", comics_path, class: 'navbar-brand' %>
        </div>

        <div class="collapse navbar-collapse" id="navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">

                <% if current_user %>
                    <li> <%= link_to current_user.email, edit_user_registration_path %></li>
                    <li><%= link_to 'Edit Profile',edit_user_registration_path %></li>
                    <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
                    <li class="round-image-50"><%= image_tag(current_user.avatar.url(:thumb)) %></li>
                <% else %>
                    <li><%= link_to 'Sign Up', new_user_registration_path %></li>

                    <li><%= link_to 'Login', new_user_session_path %></li>
                <% end %>
            </ul>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ink-About-It</title>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag asset_path('Comic_Icon.png'), :rel => 'icon', :type =>  'image/png' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>
      @import url('https://fonts.googleapis.com/css?family=Pangolin|Shadows+Into+Light|Gloria+Hallelujah|Permanent+Marker');
    </style>
  </head>

  <body>
    <%= render "layouts/menu" %>
    <div class="container">
      <%= flash[:alert] %>
      <%= flash[:notice] %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<div class="container">
  <div class="title_container">
    <h1 id="comics"><%= @comic.title %></h1>
  </div>

<ul style="list-style-type:none">
  <h2>All Pages:</h2>
   <% @page.each do |page| %>
   <li>
     <div class="well">
       <b><%= page.number %></b>
       <br>

       <%= image_tag(page.image.url(:thumb)) %>
       <br>

   </li>
   <% end %>
 </ul>


   <button class="btn btn-info"><%= link_to "Add Page", new_comic_page_path %></button>

   <button type="button" name="button">Eventually link to next page</button>
 </div>

app/views/pages/new.html.erb
<h1>Add Pages</h1>
<%= form_for [@comic, @page] do |f| %>
<div class="form-group">
    <%= f.label :image, class: 'col-sm-2 control-label'  %>
    <div class="col-sm-6">
        <%= f.file_field :image %>
    </div>
</div>
<br><br>
<%= f.hidden_field :comic_id %>

<%= f.label :number %>
<%= f.number_field :number %>

<div class="actions">
  <%= f.submit "Create" %>
</div>
<% end %>

app/views/welcome/index.html.erb
<div class="title_container">
  <h1>Ink About It!</h1>
</div>

<div class="welcome_container">

    <h3>Welcome to <span id="marker">Ink About It</span>, a place to publish and share your comics projects. Log in or sign up to get started! Start with your cover, and upload your pages as you create them.</h3>
    <br>
    <br>

<div class="right">
  <%= link_to "Sign up now!", new_user_registration_path, class: "btn btn-lg btn-primary" %>
</div>
</div>